name: Ontology Documentation CI
# copy from https://github.com/opengeospatial/ogc-geosparql/blob/master/.github/workflows/pylode.yml
on: 
  push: 
      branches:
          - master
jobs:
  build:

    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Create Ontology Documentation 🔧
      run: |
         sudo apt-get install python3 python3-setuptools python3-pip -y
         sudo apt-get install gcc libpq-dev -y
         sudo apt-get install python-dev python3-pip -y
         sudo apt-get install asciidoctor ruby -y
         sudo gem install --pre asciidoctor-pdf
         sudo apt-get install python3-dev python3-pip python3-venv python3-wheel -y
         sudo pip3 install wheel pylode
         mkdir docs

         #cp index.html docs/index.html
         cd docs
         cp ../../1.0/geo.ttl ../../1.0/profile.ttl ../../1.0/funcsrules.ttl ../../1.0/sf_geometries.ttl ../../1.0/11-052r4_OGC_GeoSPARQL.pdf .
         pylode -i ../../1.0/geo.ttl -o index.html
         pylode -i ../../1.0/profile.ttl -o profile.html -p prof
         pylode -i ../../1.0/funcsrules.ttl -o funcsrules.html -p vocpub
         pylode -i ../../1.0/sf_geometries.ttl -o sf_geometries.html -p vocpub
         #pylode -u http://schemas.opengis.net/gml/3.2.1/gml_32_geometries.rdf -o gml_geometries.html -p vocpub
         cd ../geosparql11/
         asciidoctor ../../1.1/spec/00-GeoSPARQL.adoc -o spec.html
         asciidoctor-pdf ../../1.1/spec/00-GeoSPARQL.adoc -o spec.pdf
         cp ../../1.1/geo.ttl ../../1.1/profile.ttl ../../1.1/funcsrules.ttl ../../1.1/sf_geometries.ttl ../../1.1/validation.ttl ../../1.1/sa_functions.ttl .
         cp -r ../../1.1/spec/img .
         pylode -i ../../1.1/geo.ttl -o index.html
         pylode -i ../../1.1/profile.ttl -o profile.html -p prof
         pylode -i ../../1.1/funcsrules.ttl -o funcsrules.html -p vocpub
         pylode -i ../../1.1/sf_geometries.ttl -o sf_geometries.html -p vocpub
         pylode -i ../../1.1/sa_functions.ttl -o sa_functions.html -p vocpub
         #pylode -u http://schemas.opengis.net/gml/3.2.1/gml_32_geometries.rdf -o gml_geometries.html -p vocpub
         #pylode -i ../../1.1/validation.ttl -o validation.html
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         BRANCH: gh-pages
         FOLDER: docs/
© 2021 GitHub, Inc.
